### ISSUE TITLE
Recursive

### ISSUE THREAD

**Issue by octonion** [drj11/sixtyforth#7]
How difficult is implementing "recursive"? e.g. this factorial code:

```forth
: fac recursive
  dup 1 > if
    dup 1 - fac *
  else
    drop 1
  then ;
 
: lp
  swap 1 + swap
  do
    i . i ." ! = " i fac . cr
  loop ;
 
20 0 lp
```
  Actually, I've answered my own question - "recursive" is unnecessary in your implementation!

**Comment by drj11** [comment]
so, yes, `recursive` is unnecessary, but that fact is a violation of the ANSI standard.
It annoys me too, but it will change to be ANSI compliant at some point.

ANSI programs are supposed to use `RECURSE`:

    : fac ?DUP IF  DUP 1- RECURSE *  ELSE  1  THEN ;

and `RECURSE` is implemented.
